select * from customer;
--Q1 what is the total revenue generated by male vs female
select gender, sum(purchase_amount)AS revenue
from customer
group by gender;

--Q2 which customer used a discount but still spent the more than the average amount 

select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);


--Q3 which are the top 5 products with the highest everage review rating?

select item_purchased ,avg(review_rating) as average_product_rating
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4 compare the average purchase amounts between standard and express shipping
select shipping_type,avg(purchase_amount) as new_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


--Q5 do subscribed customer spend more? compare average sepnd and total revenue between subscribers and non subscribers
select subscription_status,
count(customer_id) as total_customer,
avg(purchase_amount)as average_spend,
sum(purchase_amount)as total_revenue
from customer
group by subscription_status
order by average_spend,total_revenue desc;

--Q6 which  5 products have the highest percantage of purchases with discount applied

select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7 segment customers into new, returing,  and loyal baseed on their  total no of previous purchases, and show the  count of each segment

with customer_type as (
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal' end as customer_segment
	from customer
)
select customer_segment,count(*) as total_customer
from customer_type
group by customer_segment;

--Q8 what are the top 3 most purchased product  within each category

with customer_rank as(
    select item_purchased,category,
	count(customer_id) as total_orders,
	Row_number() over (partition by category order by count(customer_id)desc) as item_rank
	from customer
	group by item_purchased,category
)
   select item_rank,item_purchased,category,total_orders
   from customer_rank
   where item_rank<=3;

--Q9 are customera who are repeat buyers (more than 5 purchase ) also likely to subscriber?
select subscription_status,
count(customer_id) as repeat_buyer
from customer
 where previous_purchases >=5
 group by subscription_status;
 

--Q10  what is the revenue contribution by each age group

   select age_group,
   sum(purchase_amount) as total_revenue
   from customer
   group by age_group
   order by total_revenue desc;
